name: marketing_attribution

profile: miro_assignment

version: '1.1.1'
config-version: 2
require-dbt-version: ">=1.0.2"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

seeds:
    data:
    enabled: true
    +quote_columns: false

quoting:
    database: true # translates to gcp project
    identifier: true
    schema: true # translates to gcp dataset

models:
    marketing_attribution:
        materialzed: view
